core/views.py
from flask import Blueprint, render_template, make_response, send_from_directory, url_for, redirect
from models import Page,Category,Tag
from sqlalchemy import extract
from bs4 import BeautifulSoup
import datetime

core_bp = Blueprint('core_bp',__name__,template_folder='templates')

@core_bp.route('/')
@core_bp.route('/page/<int:page>')
def index(page=1):
    per_page=5
    posts = Page.query.filter_by(published=True).order_by(Page.created.desc()).paginate(page,per_page,error_out=False)
    recent_posts = Page.query.filter_by(published=True).order_by(Page.created.desc()).limit(5)
    archives = Page.query.filter_by(published=True).group_by(extract('year',Page.created),extract('month',Page.created)).order_by(Page.created.desc()).all()
    categories = Category.query.all()
    referer = "index"
    return render_template('core/index.html',posts=posts,recent_posts=recent_posts,archives=archives,categories=categories, ref=referer)

@core_bp.route('/category/<string:slug>/')
@core_bp.route('/category/<string:slug>/<int:page>')
def category(slug,page=1):
    per_page=5
    posts = Page.query.join(Category.pages).filter(Category.slug==slug,Page.published==True).order_by(Page.created.desc()).paginate(page,per_page,error_out=False)
    recent_posts = Page.query.filter_by(published=True).order_by(Page.created.desc()).limit(5)
    archives = Page.query.filter_by(published=True).group_by(extract('year',Page.created),extract('month',Page.created)).order_by(Page.created.desc()).all()
    categories = Category.query.all()
    return render_template('core/category.html',posts=posts,recent_posts=recent_posts,categories=categories,archives=archives,slug=slug)

@core_bp.route('/tag/<string:slug>/')
@core_bp.route('/tag/<string:slug>/<int:page>')
def tag(slug,page=1):
    per_page=5
    posts = Page.query.join(Tag.pages).filter(Tag.slug==slug,Page.published==True).order_by(Page.created.desc()).paginate(page,per_page,error_out=False)
    recent_posts = Page.query.filter_by(published=True).order_by(Page.created.desc()).limit(5)
    archives = Page.query.filter_by(published=True).group_by(extract('year',Page.created),extract('month',Page.created)).order_by(Page.created.desc()).all()
    categories = Category.query.all()
    return render_template('core/tag.html',posts=posts,recent_posts=recent_posts,categories=categories,archives=archives,slug=slug)

@core_bp.route('/<string:slug>/')
def page(slug):
    requested_post = Page.query.filter_by(slug=slug,published=True).first_or_404()
    recent_posts = Page.query.filter_by(published=True).order_by(Page.created.desc()).limit(5)
    archives = Page.query.filter_by(published=True).group_by(extract('year',Page.created),extract('month',Page.created)).order_by(Page.created.desc()).all()
    prev_post = Page.query.filter_by(published=True,id=requested_post.id-1).first()
    next_post = Page.query.filter_by(published=True,id=requested_post.id+1).first()
    categories = Category.query.all()
    if post:
        return render_template('core/post.html',prev=prev_post,next=next_post,post=requested_post,date=datetime.datetime.strftime(requested_post.created, "%d %B %Y"),short=BeautifulSoup(requested_post.content,"html.parser").text.lstrip().rstrip()[0:52],recent_posts=recent_posts,categories=categories,archives=archives)
    else:
        return render_template('index.html')

@core_bp.route('/<int:year>/<int:month>/<string:slug>/')
def post(year,month,slug):
    requested_post = Page.query.filter(extract('year',Page.created)==year,extract('month',Page.created)==month).filter_by(slug=slug,published=True).first_or_404()
    prev_post = Page.query.filter_by(published=True,id=requested_post.id-1).first()
    next_post = Page.query.filter_by(published=True,id=requested_post.id+1).first()
    if post:
        return render_template('core/post.html',prev=prev_post,next=next_post,post=requested_post,date=datetime.datetime.strftime(requested_post.created, "%d %B %Y"),short=BeautifulSoup(requested_post.content,"html.parser").text.lstrip().rstrip()[0:52])
    else:
        return render_template('index.html')

@core_bp.route('/<int:year>/<int:month>/')
def month(year,month,page=1):
    per_page=5
    posts = Page.query.filter(extract('year',Page.created)==year,extract('month',Page.created)==month).filter_by(published=True).order_by(Page.created.desc()).paginate(page,per_page,error_out=False)
    recent_posts = Page.query.filter_by(published=True).order_by(Page.created.desc()).limit(5)
    archives = Page.query.filter_by(published=True).group_by(extract('year',Page.created),extract('month',Page.created)).order_by(Page.created.desc()).all()
    categories = Category.query.all()
    if posts:
        return render_template('core/month.html',posts=posts,year=year,month=month,recent_posts=recent_posts,categories=categories,archives=archives)
    else:
        return render_template('index.html')

@core_bp.route('/p/<int:postid>/')
def post_by_id(postid):
    requested_post = Page.query.filter_by(id=postid,published=True).first_or_404()
    prev_post = Page.query.filter_by(published=True,id=requested_post.id-1).first()
    next_post = Page.query.filter_by(published=True,id=requested_post.id+1).first()
    if post:
        return render_template('core/post.html',prev=prev_post,next=next_post,post=requested_post,date=datetime.datetime.strftime(requested_post.created, "%d %B %Y"),short=BeautifulSoup(requested_post.content,"html.parser").text.lstrip().rstrip()[0:52])
    else:
        return render_template('index.html')

@core_bp.route('/category/<string:slug>/feed/')
def category_feed(slug):
    pages = Page.query.join(Category.pages).filter(Page.published==True,Category.slug==slug).order_by(Page.created.desc()).limit(10)
    for page in pages:
        page.content = page.content.replace('&oacute;','ó').replace('&ndash;',' ').replace('&nbsp;',' ')
    template = render_template('core/feed.html',pages=pages,slug=slug)
    response = make_response(template)
    response.headers['Content-Type'] = 'application/xml'
    return response

@core_bp.route('/feed/')
def main_feed():
    pages = Page.query.filter_by(published=True).order_by(Page.created.desc()).limit(20)
    for page in pages:
        page.content = page.content.replace('&oacute;','ó').replace('&ndash;',' ').replace('&nbsp;',' ')
    template = render_template('core/feed.html',pages=pages)
    response = make_response(template)
    response.headers['Content-Type'] = 'application/xml'
    return response


@core_bp.route('/raport_klifowy.pdf')
def raport_klifowy():
    return redirect(url_for('static',filename='raport_klifowy.pdf'))

@core_bp.route('/raport_sudety.pdf')
def raport_sudety():
    return redirect(url_for('static',filename='raport_sudety.pdf'))

@core_bp.route('/raport_beskidwyspowy.pdf')
def raport_beskid_wyspowy():
    return redirect(url_for('static',filename='raport_beskidwyspowy.pdf'))

@core_bp.route('/weather_forecast.pdf')
def raport_all():
    return redirect(url_for('static',filename='weather_forecast.pdf'))

core/templates/core/_helpers.html
{% macro display_archives(archives) -%} 
<h3 class="widget-title">Archiwa</h3>
			<ul>
	{% for post in archives %}
	<li><a href='{{ url_for('core_bp.month',year=post.created.year,month=post.created.month) }}'>{{ post.created.month |month_name }} / {{ post.created.year }}</a></li>
	{% endfor %}
	</ul>
{%- endmacro %} 

{% macro display_recent_posts(recent_posts) -%} 
<h3 class="widget-title">Najnowsze wpisy</h3>
<ul>
	{% for post in recent_posts %}
		<li><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}">{{ post.title }}</a></li>
	{% endfor %}
</ul>
{%- endmacro %} 


{% macro display_categories(categories) -%} 
<ul>
	{% for category in categories %}
		<li class="cat-item cat-item-2"><a href="{{ url_for('core_bp.category',slug=category.slug) }}"> {{ category.name }}</a>
	{% endfor %}
</ul>

			</aside><aside id="meta-2" class="widget widget_meta"><h3 class="widget-title">Meta</h3>
		<ul>
			<li><a href="http://pgxc.pl/feed/">Kanał wpisów</a></li>
		</ul>

{%- endmacro %} 

{% macro display_menu() -%}
<div class="menu-menu-1-container"><ul id="menu-menu-1" class="menu"><li id="menu-item-46" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-home menu-item-46"><a href="{{ url_for('core_bp.index') }}">Strona główna</a></li><li id="menu-item-48" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-48" style="pointer-events:none"><a href="#">Raporty pogodowe:</a></li>
                                                <li id="menu-item-48" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-48"><a href="{{ url_for('core_bp.page',slug='klifowy-raport-pogodowy') }}">Klifowy</a></li>
                                                <li id="menu-item-275" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-275"><a href="{{ url_for('core_bp.page',slug='sudety-raport-pogodowy') }}">Sudety</a></li>
                                                <li id="menu-item-275" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-275"><a href="{{ url_for('core_bp.page',slug='beskid-wyspowy-raport-pogodowy') }}">Beskid Wyspowy</a></li>
<li id="menu-item-49" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-49"><a href="https://leonardo.pgxc.pl">Polski Serwer LeonardoXC &#8211; leonardo.pgxc.pl</a></li>
</ul></div>
{%- endmacro %}

core/templates/core/category.html
{% extends 'core/base.html' %}

{% from 'core/_helpers.html' import display_archives,display_recent_posts,display_categories %} 
{% block header %}
<header class="page-header"><h1 class="page-title">Archiwum kategorii: <span>{{ slug }}</span></h1> </header>
{% endblock %}


{% block content %}

{% for post in posts.items %}

					
<article id="post-{{ post.id }}" class="post-{{ post.id }} post type-post status-publish format-standard hentry category-aktualnosci category-leonardoxc tag-best-of-the-best tag-loty-holowane tag-ranking">
		<header class="entry-header">
			<h1 class="entry-title"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" rel="bookmark">{{ post.title }}</a></h1>
			
						<div class="entry-meta">
							<span class="sep">Opublikowany </span><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" title="11:42 am" rel="bookmark"><time class="entry-date" datetime="{{ post.created }}+00:00">{{ post.created.day }} {{ post.created.month | month_name }}, {{ post.created.year }}</time></a><span class="by-author"> <span class="sep"> przez </span> <span class="author vcard"><a class="url fn n" href="http://pgxc.pl/author/rgrubba/" title="Zobacz wszystkie wpisy, których autorem jest rgrubba" rel="author">rgrubba</a></span></span>			</div><!-- .entry-meta -->
			
						<div class="comments-link">
							<a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Odpowiedz</span></a>			</div>
					</header><!-- .entry-header -->
					
					{{ post.content |safe }}

					<!-- .entry-content -->
		
		<footer class="entry-meta">
			
	<span class="cat-links">
		<span class="entry-utility-prep entry-utility-prep-cat-links">Zaszufladkowano do kategorii</span>{% for cat in post.categories %} <a href="{{ url_for('core_bp.category',slug=cat.slug) }}" rel="category tag">{{ cat.name }}</a>,{% endfor %} </span>
							
										<span class="sep"> | </span>
	<span class="tag-links">
	<span class="entry-utility-prep entry-utility-prep-tag-links">Otagowano</span> {% for tag in post.tags %} <a href="{{ url_for('core_bp.tag',slug=tag.slug) }}" rel="tag">{{ tag.name }}</a>,{% endfor %}</span>
							
										<span class="sep"> | </span>
										<span class="comments-link"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Dodaj komentarz</span></a></span>
			
					</footer><!-- .entry-meta -->
	</article><!-- #post-{{ post.id }} -->
{% endfor %}

<nav id="nav-below">
	<h3 class="assistive-text">Zobacz wpisy</h3>
		{% if posts.has_prev %} <div class="nav-previous"><a href="{{ url_for('core_bp.category',page=posts.prev_num,slug=slug) }}" ><span class="meta-nav">&larr;</span> Nowsze wpisy</a></div> {% endif %}
		{% if posts.has_next %} <div class="nav-next"> <a href="{{ url_for('core_bp.category',page=posts.next_num,slug=slug) }}" >Starsze wpisy <span class="meta-nav">&rarr;</span></a> </div> {% endif %}
</nav><!-- #nav-above -->
{% endblock %}

{% block recent_posts %}
{{ display_recent_posts(recent_posts) }}
{% endblock %}

{% block archives %}
{{ display_archives(archives) }}
{% endblock %}

{% block categories %}
{{ display_categories(categories) }}
{% endblock %}

core/templates/core/feed.html
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Aktualności &#8211; pgxc.pl</title>
	<atom:link href="http://pgxc.pl/category/{{ slug }}/feed/" rel="self" type="application/rss+xml" />
	<link>https://pgxc.pl</link>
	<description>Polski Serwer LeonardoXC</description>
	<lastBuildDate>{{ pages[1].created | xmltime }}+0000</lastBuildDate>
	<language>pl-PL</language>
	<sy:updatePeriod>daily</sy:updatePeriod>
	<sy:updateFrequency>1	</sy:updateFrequency>
	<generator>Simple Flask Blog</generator>
	{% for page in pages %}
		<item>
			<title>{{ page.title }}</title>
			<link>http://pgxc.pl/{{ page.created.year }}/{{ page.created.month }}/{{ page.slug }}</link>
		
			<dc:creator><![CDATA[Robert Grubba]]></dc:creator>
			<pubDate>{{ page.created |xmltime }}+0000</pubDate>
			{% for category in page.categories %}
				<category><![CDATA[{{ category.name }}]]></category>
			{% endfor %}	
				<guid isPermaLink="false">http://pgxc.pl/p/{{ page.id }}</guid>

				<description><![CDATA[ {{ page.content | striptags | truncate(255, True) }}]]></description>
			<content:encoded> {{ page.content |safe }}
			</content:encoded>
		</item>
	{% endfor %}
</channel>
</rss>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% from 'core/_helpers.html' import display_archives,display_recent_posts,display_categories %} 
{% block content %}

{% for post in posts.items %}

					
<article id="post-{{ post.id }}" class="post-{{ post.id }} post type-post status-publish format-standard hentry category-aktualnosci category-leonardoxc tag-best-of-the-best tag-loty-holowane tag-ranking">
		<header class="entry-header">
			<h1 class="entry-title"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" rel="bookmark">{{ post.title }}</a></h1>
			
						<div class="entry-meta">
							<span class="sep">Opublikowany </span><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" title="11:42 am" rel="bookmark"><time class="entry-date" datetime="{{ post.created }}+00:00">{{ post.created.day }} {{ post.created.month | month_name }}, {{ post.created.year }}</time></a><span class="by-author"> <span class="sep"> przez </span> <span class="author vcard"><a class="url fn n" href="http://pgxc.pl/author/rgrubba/" title="Zobacz wszystkie wpisy, których autorem jest rgrubba" rel="author">rgrubba</a></span></span>			</div><!-- .entry-meta -->
			
						<div class="comments-link">
							<a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Odpowiedz</span></a>			</div>
					</header><!-- .entry-header -->
					
					{{ post.content |safe }}

					<!-- .entry-content -->
		
		<footer class="entry-meta">
			
		<span class="cat-links">
			<span class="entry-utility-prep entry-utility-prep-cat-links">Zaszufladkowano do kategorii</span> {% for cat in post.categories %} <a href="{{ url_for('core_bp.category',slug=cat.slug) }}" rel="category tag">{{ cat.name }}</a>, {% endfor %}
			</span>
		<span class="sep"> | </span>
		<span class="tag-links">
			<span class="entry-utility-prep entry-utility-prep-tag-links">Otagowano</span> {% for tag in post.tags %} <a href="{{ url_for('core_bp.tag',slug=tag.slug) }}" rel="tag">{{ tag.name }}</a>, {% endfor %} </span>
							
										<span class="sep"> | </span>
										<span class="comments-link"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Dodaj komentarz</span></a></span>
			
					</footer><!-- .entry-meta -->
	</article><!-- #post-{{ post.id }} -->
{% endfor %}

<nav id="nav-below">
	<h3 class="assistive-text">Zobacz wpisy</h3>
	{% if ref=="index" %}
		{% if posts.has_prev %} <div class="nav-previous"><a href="{{ url_for('core_bp.index',page=posts.prev_num) }}" ><span class="meta-nav">&larr;</span> Nowsze wpisy</a></div> {% endif %}
		{% if posts.has_next %} <div class="nav-next"> <a href="{{ url_for('core_bp.index',page=posts.next_num) }}" >Starsze wpisy <span class="meta-nav">&rarr;</span></a> </div> {% endif %}
	{% endif %}
	{% if ref=="category" %}
		{% if posts.has_prev %} <div class="nav-previous"><a href="{{ url_for('core_bp.category',page=posts.prev_num) }}" ><span class="meta-nav">&larr;</span> Nowsze wpisy</a></div> {% endif %}
		{% if posts.has_next %} <div class="nav-next"> <a href="{{ url_for('core_bp.category',page=posts.next_num) }}" >Starsze wpisy <span class="meta-nav">&rarr;</span></a> </div> {% endif %}
	{% endif %}
</nav><!-- #nav-above -->
{% endblock %}

{% block recent_posts %}
{{ display_recent_posts(recent_posts) }}
{% endblock %}

{% block archives %}
{{ display_archives(archives) }}
{% endblock %}

{% block categories %}
{{ display_categories(categories) }}
{% endblock %}

core/templates/core/month.html
{% extends 'core/base.html' %}
{% from 'core/_helpers.html' import display_archives,display_recent_posts,display_categories %} 

{% block header %}
<header class="page-header"><h1 class="page-title">Miesięczne archiwum: <span>{{ posts.items[0].created.month|month_name }} {{posts.items[0].created.year }}</span></h1> </header>
{% endblock %}

{% block content %}

{% for post in posts.items %}

					
<article id="post-{{ post.id }}" class="post-{{ post.id }} post type-post status-publish format-standard hentry category-aktualnosci category-leonardoxc tag-best-of-the-best tag-loty-holowane tag-ranking">
		<header class="entry-header">
			<h1 class="entry-title"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" rel="bookmark">{{ post.title }}</a></h1>
			
						<div class="entry-meta">
							<span class="sep">Opublikowany </span><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" title="11:42 am" rel="bookmark"><time class="entry-date" datetime="{{ post.created }}+00:00">29 października, 2020</time></a><span class="by-author"> <span class="sep"> przez </span> <span class="author vcard"><a class="url fn n" href="http://pgxc.pl/author/rgrubba/" title="Zobacz wszystkie wpisy, których autorem jest rgrubba" rel="author">rgrubba</a></span></span>			</div><!-- .entry-meta -->
			
						<div class="comments-link">
							<a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Odpowiedz</span></a>			</div>
					</header><!-- .entry-header -->
					
					{{ post.content |safe }}

					<!-- .entry-content -->
		
		<footer class="entry-meta">
	
		<span class="cat-links">
			<span class="entry-utility-prep entry-utility-prep-cat-links">Zaszufladkowano do kategorii</span> {% for cat in post.categories %}<a href="{{ url_for('core_bp.category',slug=cat.slug) }}" rel="category tag">{{ cat.name }}</a>, {% endfor %}	</span>
							
										<span class="sep"> | </span>
		<span class="tag-links">
			<span class="entry-utility-prep entry-utility-prep-tag-links">Otagowano</span> {% for tag in post.tags %} <a href="{{ url_for('core_bp.tag',slug=tag.slug) }}" rel="tag">{{ tag.name }}</a>,{% endfor %}</span>
							
										<span class="sep"> | </span>
										<span class="comments-link"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Dodaj komentarz</span></a></span>
			
					</footer><!-- .entry-meta -->
	</article><!-- #post-{{ post.id }} -->
{% endfor %}

<nav id="nav-below">
	<h3 class="assistive-text">Zobacz wpisy</h3>
	{% if posts.has_prev %} <div class="nav-previous"><a href="{{ url_for('core_bp.month',page=posts.prev_num,year=year,month=month) }}" ><span class="meta-nav">&larr;</span> Nowsze wpisy</a></div> {% endif %}
	{% if posts.has_next %} <div class="nav-next"> <a href="{{ url_for('core_bp.month',page=posts.next_num,year=year,month=month) }}" >Starsze wpisy <span class="meta-nav">&rarr;</span></a> </div> {% endif %}
</nav><!-- #nav-above -->
{% endblock %}

{% block recent_posts %}
{{ display_recent_posts(recent_posts) }}
{% endblock %}

{% block archives %}
{{ display_archives(archives) }}
{% endblock %}

{% block categories %}
{{ display_categories(categories) }}
{% endblock %}

core/templates/core/post.html
{% extends 'core/base_post.html' %}

{% block header %}
  <h1>TEST HEADER</h1>
{% endblock %}

{% block content %}
{% if post.content |safe |startswith %}
	{{ post.content|safe }}
{% else %}
	<div class="entry-content">
		{{ post.content|safe }}
	</div>
{% endif %}

<footer class="entry-meta">
	Kategorie: {% for cat in post.categories %} <a href="{{ url_for('core_bp.category',slug=cat.slug) }}" rel="category tag">{{ cat.name }}</a>, {% endfor %} Tagi: {% for tag in post.tags %}<a href="{{ url_for('core_bp.tag',slug=tag.slug) }}" rel="tag">{{ tag.name }}</a>,{% endfor %}. Dodaj zakładkę do <a href="http://pgxc.pl{{ request.path }}" title="Bezpośredni odnośnik do &#8222;Ponadczasowy Paralotniowy Ranking Lotów Holowanych&#8221;" rel="bookmark">bezpośredniego odnośnika</a>.
		
			</footer><!-- .entry-meta -->
{% endblock %}

core/templates/core/tag.html
{% extends 'core/base.html' %}
{% from 'core/_helpers.html' import display_archives,display_recent_posts,display_categories %} 

{% block header %}
<header class="page-header"><h1 class="page-title">Archiwa tagu: <span>{{ slug }}</span></h1> </header>
{% endblock %}


{% block content %}

{% for post in posts.items %}

					
<article id="post-{{ post.id }}" class="post-{{ post.id }} post type-post status-publish format-standard hentry category-aktualnosci category-leonardoxc tag-best-of-the-best tag-loty-holowane tag-ranking">
		<header class="entry-header">
			<h1 class="entry-title"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" rel="bookmark">{{ post.title }}</a></h1>
			
						<div class="entry-meta">
							<span class="sep">Opublikowany </span><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}" title="11:42 am" rel="bookmark"><time class="entry-date" datetime="{{ post.created }}+00:00">{{ post.created.day }} {{ post.created.month | month_name }}, {{ post.created.year }}</time></a><span class="by-author"> <span class="sep"> przez </span> <span class="author vcard"><a class="url fn n" href="http://pgxc.pl/author/rgrubba/" title="Zobacz wszystkie wpisy, których autorem jest rgrubba" rel="author">rgrubba</a></span></span>			</div><!-- .entry-meta -->
			
						<div class="comments-link">
							<a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Odpowiedz</span></a>			</div>
					</header><!-- .entry-header -->
					
					{{ post.content |safe }}

					<!-- .entry-content -->
		
		<footer class="entry-meta">
			<span class="cat-links">
			<span class="entry-utility-prep entry-utility-prep-cat-links">Zaszufladkowano do kategorii</span> {% for cat in post.categories %} <a href="{{ url_for('core_bp.category',slug=cat.slug) }}" rel="category tag">{{ cat.name }}</a>,{% endfor %} </span>
							
										<span class="sep"> | </span>
			<span class="tag-links">
				<span class="entry-utility-prep entry-utility-prep-tag-links">Otagowano</span> {% for tag in post.tags %}<a href="{{ url_for('core_bp.tag',slug=tag.slug) }}" rel="tag">{{ tag.name }}</a>, {% endfor %}	</span>
							
										<span class="sep"> | </span>
										<span class="comments-link"><a href="{{ url_for('core_bp.post',year=post.created.year,month=post.created.month,slug=post.slug) }}#respond"><span class="leave-reply">Dodaj komentarz</span></a></span>
			
					</footer><!-- .entry-meta -->
	</article><!-- #post-{{ post.id }} -->
{% endfor %}

<nav id="nav-below">
	<h3 class="assistive-text">Zobacz wpisy</h3>
		{% if posts.has_prev %} <div class="nav-previous"><a href="{{ url_for('core_bp.tag',page=posts.prev_num,slug=slug) }}" ><span class="meta-nav">&larr;</span> Nowsze wpisy</a></div> {% endif %}
		{% if posts.has_next %} <div class="nav-next"> <a href="{{ url_for('core_bp.tag',page=posts.next_num,slug=slug) }}" >Starsze wpisy <span class="meta-nav">&rarr;</span></a> </div> {% endif %}
</nav><!-- #nav-above -->
{% endblock %}

{% block recent_posts %}
{{ display_recent_posts(recent_posts) }}
{% endblock %}

{% block archives %}
{{ display_archives(archives) }}
{% endblock %}

{% block categories %}
{{ display_categories(categories) }}
{% endblock %}